sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=burlak.javascript.ru
    - secure: >-
        hzmFjD21K8h06XBI8QgiclRg9Vl49lFomrdfnOdrose7+NWnFSqH4etB0ytiXFbtSdjWunHSElMOco5T4Gim/fUgUxhQtez49P92LMyW/9YlfPI6b5ZsJRHQX/9hVGD3l8pPRJdQdQYxiX03R279nkk9Tbj0crAA+USXfnMRWp47f+uL4mzXDXFHElsvg+KdYaL+m9bRWFpzfHn4EsxwXsU++AmEn2jNB4gcgYkMnh/Vf76TJeWdYJLS0IG5G84itKIeKnCv5aw02aYe90iMhrkS1TeKEBkHdN56H51QQ9CCtnM4N48fIjvZ3KryA4+tswn3dQaCS6jjwTd6J42g3MuslGBsCEgy8PZ+iJFykGx8kaW6qZoUxdzKfj2SvPlqKrgMfcUCCg/UeqGa6OwplBNR39AnLxytDtawcOgogFb4AR7GE7e/um/c6xe553ez3pGfj5xYkRO/bHmlbHCfLddt7dhDkG5vHtRSxgZmmQrCpQkcJCInD63Jl0G2+9NTGdYYMMH6i+jcA/8MQNWiBjNw7OzBCd2ckRSEjGU9efStk8oiMxsz2VWQ8tXD/Dfycw0yoCZlOamUe9nHA18mT/CpKvidsyAm74pB5QiMCrP448X+WV6pB5FRC/gtilJDW8tytDnwFe88tf0v649gsx+rd6F0Iar7UPPLg6JAqHQ=
    - secure: >-
        tNW1YlStvkMV+rTebAG2v1Wi4pb9NxNHSTRJlAV4S0JkxvVPBCCZaot+sIjFWt7rGLLT4fUeSdADwudHbkZZLIqOeIAaPfi0KJHC9r0Pz2C8WIAUuZXOih1K3K/AiEFdvnSXJvCq2fmnBsvbk29Atc+XRPdEzfDq1yVxpAo9VnHTTXXit+YzVKzEDVuSt0r6aXhpTjYfaN+Ag8szFuIeoRfhzQ1dpVxSUNQG1XCIPpWM/WHp73Gl/JWmTySPTP33KVMw7WAtdwAQvDCsdOUYP72hJy7kxFLlVoO98nRdBUkjtp6mAQbIPeMWce5+Q2PtevlJB7w9SuUQBWAjtvOO0mSLxyL4A9qHCPclre0jZ8N1bZ3TzrGtITAia3tWbdAwHgMoI+ouAw0an3wYU7tQbhVPhofHl2ZqLLL1t05JP1JC0vwtflapo1/eCCmtV8/54O8AqgV0MZFf2zGFaGgalYaGAMDtdGE4TNhHXeFiqki6MMYyZeeTJZAAnz5rbDiOAfvtiurRNyHXLUWJ9WRruDDpag+/r6TqH1Ax9zu+cqawbsVvs+CsnwU/d/kNsQY8slLXQweyKkshXB46BjSLds7bu9EC9PZ5m7nL2vNAg8Rp9iZVCOK1Zq4mDWpf5qsd2YPX7Dh/8+yxkbNhf7cu7OYTAE5HSOsEpYV6xHa/Mbs=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
