sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        WPliWKAcocyZc6fMp18dlztSgQ+fy9zdPP+PHON3Gi89eiG38L9WMytgNR3AVEBgzC+mGCYTwtaccRu1pJmG6ceZDt01bbo5ddzZ6a/oBBq0tcvDudeAHzxbtOOTakXNtC3Ww9p1J4E/alnQWUHJqsOkPt8eer9l8VmJ37a6MSpO3zFPkYR1UYMsK5UyXOrvdea5n2cpt49ygWqZii0j2Wf4my1pW+64dshig7P2sovG3xTnmZ099ps/sa3wukZtDelXmrKD4EuhusjFN6bZCUPd4rOuyd+t8Z2Y4zvThgQXl3G9HTv+mSUJamdIuYbY46QiTnnGbuF646jgoQrodcN/pdAx16LM0DcEiraGIp9Ax4UhaGAf6Mpwqq+mwiwO0PMUoyf/HKeNUt6oHD7/dH5dCL+QjvFp+SwwXgs2TKcvdfmIjPO0v4rcNh/4HpfW1bXHb2fB4+etLlRMuVzAWQyW7f9JhQgqKRDl4aKod+H6CCJXAGg8nv+N0t91ltxSEP0qIlFyxnIoR78vSdm5g2VyjIBIQirDCB/THaaiWJ4hlxdk694fmZwvbYJTkxvb9IJhZ/uq5aIqgSue4HjFJckh+Sn7mfATF26qIkjg0cTF3iEcsuNG/fWL/wkfO5xaOJ3Cy+pYCLoA1CyAmWK5uHGV5iE2ZTDqFjIWPEbJOaE=
    - secure: >-
        SFzPXhD8I9cC6w5kit2Z/mBNjewB0rzvNNNG2NjdkEBai2n5YMUG5MqOMNOhz4dcs298WSmquKyT1m3ZwNv8yTtrqT87OCJNRYoohzWkwJlk/tT/YbqDMARqiG4QnHaLOZS0P4RIx/3tzQYUeK46iA2wIrkm8pIuYy5K8PSYtrh34KWjpJJAV5F97EY5alTEW9ypS8ebxyVzUzjDtPRSPiM6WGlhZTENuZ85ozdeAeE6R+5HgeyvRRr2HAFA3ulVnDxwpcV8301h0dse3IS8xQYMyZKajKLJ8fONa7pNZhvAHOwEnEaXKmy/S4avkPn14qT/tjz9reJnAWE/ASaJjrLUy7IUym/vq1kGrwaQ1ERk86VHmoSOZW35uGsbqie8zBQo1siSif5e+qMmqtON3kqg/67IefPbp4Wpe7E12wO/jHne7Nv7MOjxzhzSsULY4AW8fi4BBTXCY9wZzPMnUx1dzImC0ePhamG+oTKZajJg/YbytWEalVtdh0ruReZIz+7fIPix5iipeICXURf52hvW80ZVhzWb8uGkOc7+0886H8fi4G+kHJ/6/0n/w5WY6Q56EJMviR5H1EXW3rVyDNoiDtnHAWT38N8qukSRT04XDPr5YCijI3PyLDDk5/IyupXCK9f5OcJi3UOAl5Ku1eOOCQMbmGxw3kT2ZW6UIVU=
script:
  - npm run test
notifications:
  webhooks: 'http://testhook.javascript.ru/automation/ci/build'
